# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aZBFdX-6G_Cyp_onazBceeqsMQVqUQjv
"""

import pandas as pd
import matplotlib.pyplot as plt

db = pd.read_excel('/content/drive/MyDrive/Project/try.xlsx')
db.head(10)

count=0
for i in db['Model']:
  if i =="Hyundai":
    count+=1
print(count)

db[db['Time'] <= '29.02.2024'].head()





